### ISSUE TITLE
Switch to drush for deployment flow?

### ISSUE THREAD

**Issue by daften** [digipolisgent/robo-digipolis-drupal8#5]
Problem:
When faulty config is imported, every drupal console command fails, because the bootstrap that happens on each command fails. That means the restore at the end of the failed deploy fails as well.

- First put an issue in drupal-console project if this can be fixed at a higher level.
- Replace certain drupal console commands with drush commands to make sure the flow keeps working. E.g. the database restore.

**Comment by Jelle-S** [comment]
First put an issue in drupal-console project if this can be fixed at a higher level:
https://github.com/hechoendrupal/drupal-console/issues/3216
